
[build]
  command = "npm run build-minified"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

# Add this section to prevent trailing slash redirects
[[plugins]]
package = "netlify-plugin-no-more-404"

[plugins.inputs]
  # Disable trailing slashes
  trailingSlash = false

[[redirects]]
  from = "/services/home-removals"
  to = "/services/house-removals"
  status = 301

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
